import Config

# Configure your database
config :starter_kit, StarterKit.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "starter_kit_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :starter_kit, StarterKitWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  # In development, static assets are served by the Vite dev server (HMR).
  static_url: [host: "localhost", port: 5173],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "HJ1XgHDesE2xQHUnxyHFzbR7b84JSMOv4TZUIaFkhPEhAX/v3f9KIZQJWcmi0V1w",
  # Run the Vite dev server as a watcher alongside `mix phx.server`.
  watchers: [vite: {PhoenixVite.Npm, :run, [:vite, ~w(dev)]}]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :starter_kit, dev_routes: true, token_signing_secret: "lmfm7muFcUQTO8jcDPYp6qFszXBrOVxe"

# Relax the CSP for the Vite dev server: module scripts and styles are served from
# :5173, HMR runs over a websocket, and React Fast Refresh needs 'unsafe-eval'.
config :starter_kit,
       :content_security_policy,
       "default-src 'self'; " <>
         "connect-src 'self' ws://localhost:5173 http://localhost:5173; " <>
         "img-src 'self' data:; " <>
         "style-src 'self' 'unsafe-inline' http://localhost:5173; " <>
         "script-src 'self' 'unsafe-inline' 'unsafe-eval' http://localhost:5173; " <>
         "base-uri 'self'; frame-ancestors 'self'; object-src 'none'"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
